### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by pombredanne** [endvroy/antlr4_bash#1]
I could not find a license for this repo. What would it be?
Thanks

**Comment by endvroy** [comment]
@pombredanne Hi, this repo is now under MIT license.
Please note due to the complex and undocumented nature of real-world bash grammar, there might be a lot of mishandled corner cases in this repo.

**Comment by pombredanne** [comment]
Thanks!

**Comment by sohale** [comment]
Thanks for clarifying.
Any ANTLR4 alternatives to compare it with? It seems fine to me, but I like to have a look at alternatives if there are any. (I want to use it with ANTLR4 ).
